# Generated by Django 5.2.7 on 2025-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
