# Generated by Django 5.2.7 on 2025-11-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients_en',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_it',
            field=models.CharField(default='', max_length=90),
        ),
    ]
